config/routes.rb
Rails.application.routes.draw do

  namespace :visuals do
    resources :colors
    resources :materials
    resources :parts

    resources :products do
      resources :product_colors
      resources :product_parts
    end
  end

  get 'visuals/parts', :to => 'parts#index'
  get 'visuals/products', :to => 'products#index'
  get 'visuals/:id', :to => 'products#show'

  get 'visuals/materials', :to => 'materials#index'
  get 'visuals/colors', :to => 'colors#index'
  get 'visuals/product_colors', :to => 'product_colors#index'

  mount Spree::Core::Engine, :at => '/'

end

Spree::Core::Engine.add_routes do

  get '/collection', :to => 'products#index'
  get '/products', :to => 'products#index'
  get '/about' => 'home#about', :as => :about
  get '/materials' => 'home#materials', :as => :materials
  get '/explore' => 'home#explore', :as => :explore
 get '/products/variantz', :to => 'home#variantz'

end

app/models/spree/asset.rb
module Spree
  class Asset < Spree::Base
    belongs_to :viewable, polymorphic: true, touch: true
    belongs_to :visuals_product_perspective, :class_name => 'Visuals::ProductPerspective'

    acts_as_list scope: [:viewable_id, :viewable_type]
  end
end

app/controllers/spree/content_controller.rb
module Spree
  class ContentController < Spree::StoreController
    respond_to :html

    def cvv
      render :layout => false
    end
  end
end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    def about
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    def materials
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @materials = Visuals::Material.all
    end

    def variantz
      @var = Spree::Variant.all
      @img = Spree::Image.all
    end

    def explore
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end
  end
end

app/controllers/spree/locale_controller.rb
module Spree
  class LocaleController < Spree::StoreController
    def set
      if request.referer && request.referer.starts_with?('http://' + request.host)
        session['user_return_to'] = request.referer
      end
      if params[:locale] && I18n.available_locales.map(&:to_s).include?(params[:locale])
        session[:locale] = I18n.locale = params[:locale]
        flash.notice = Spree.t(:locale_changed)
      else
        flash[:error] = Spree.t(:locale_not_changed)
      end
      redirect_back_or_default(spree.root_path)
    end
  end
end

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < Spree::StoreController
    before_action :load_product, only: :show
    before_action :load_taxon, only: :index

    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)

    end

    def show
      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @perspectives = Visuals::ProductPerspective.all
    end

    private
      def accurate_title
        if @product
          @product.meta_title.blank? ? @product.name : @product.meta_title
        else
          super
        end
      end

      def load_product
        if try_spree_current_user.try(:has_spree_role?, "admin")
          @products = Product.with_deleted
        else
          @products = Product.active(current_currency)
        end
        @product = @products.friendly.find(params[:id])
      end

      def load_taxon
        @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
      end
  end
end

app/controllers/spree/store_controller.rb
module Spree
  class StoreController < Spree::BaseController
    include Spree::Core::ControllerHelpers::Order

    skip_before_action :set_current_order, only: :cart_link

    def unauthorized
      render 'spree/shared/unauthorized', :layout => Spree::Config[:layout], :status => 401
    end

    def cart_link
      render :partial => 'spree/shared/link_to_cart'
      fresh_when(simple_current_order)
    end

    private

      # This method is placed here so that the CheckoutController
      # and OrdersController can both reference it (or any other controller
      # which needs it)
      def apply_coupon_code
        if params[:order] && params[:order][:coupon_code]
          @order.coupon_code = params[:order][:coupon_code]

          handler = PromotionHandler::Coupon.new(@order).apply

          if handler.error.present?
            flash.now[:error] = handler.error
            respond_with(@order) { |format| format.html { render :edit } } and return
          elsif handler.success
            flash[:success] = handler.success
          end
        end
      end

      def config_locale
        Spree::Frontend::Config[:locale]
      end

      def lock_order
        OrderMutex.with_lock!(@order) { yield }
      rescue Spree::OrderMutex::LockFailed => e
        flash[:error] = Spree.t(:order_mutex_error)
        redirect_to spree.cart_path
      end
  end
end

app/helpers/spree/base_helper.rb
module Spree
  module BaseHelper

    # Defined because Rails' current_page? helper is not working when Spree is mounted at root.
    def current_spree_page?(url)
      path = request.fullpath.gsub(/^\/\//, '/')
      if url.is_a?(String)
        return path == url
      elsif url.is_a?(Hash)
        return path == spree.url_for(url)
      end
      return false
    end

    def link_to_cart(text = nil)
      text = text ? h(text) : Spree.t(:cart)
      css_class = nil

      if simple_current_order.nil? or simple_current_order.item_count.zero?
        text = "(0)"
        # (#{Spree.t(:empty)})
        css_class = 'empty'
        #{text}:
      else
        text = "(#{simple_current_order.item_count})  "
        # <span class='amount'>#{simple_current_order.display_total.to_html}</span>
        css_class = 'full'
      end

      link_to text.html_safe, spree.cart_path, :class => "cart-info #{css_class}"
    end

    # human readable list of variant options
    def variant_options(v, options={})
      v.options_text
    end

    def meta_data
      object = instance_variable_get('@'+controller_name.singularize)
      meta = {}

      if object.kind_of? ActiveRecord::Base
        meta[:keywords] = object.meta_keywords if object[:meta_keywords].present?
        meta[:description] = object.meta_description if object[:meta_description].present?
      end

      if meta[:description].blank? && object.kind_of?(Spree::Product)
        meta[:description] = strip_tags(truncate(object.description, length: 160, separator: ' '))
      end

      meta.reverse_merge!({
        keywords: current_store.meta_keywords,
        description: current_store.meta_description,
      }) if meta[:keywords].blank? or meta[:description].blank?
      meta
    end

    def meta_data_tags
      meta_data.map do |name, content|
        tag('meta', name: name, content: content)
      end.join("\n")
    end

    def body_class
      @body_class ||= content_for?(:sidebar) ? 'two-col' : 'one-col'
      @body_class
    end

    def logo(image_path=Spree::Config[:logo])
      link_to image_tag(image_path), spree.root_path
    end

    def flash_messages(opts = {})
      ignore_types = ["order_completed"].concat(Array(opts[:ignore_types]).map(&:to_s) || [])

      flash.each do |msg_type, text|
        unless ignore_types.include?(msg_type)
          concat(content_tag :div, text, class: "flash #{msg_type}")
        end
      end
      nil
    end

    def breadcrumbs(taxon, separator="&nbsp;&raquo;&nbsp;", breadcrumb_class="inline")
      return "" if current_page?("/") || taxon.nil?

      crumbs = [[Spree.t(:home), spree.root_path]]

      if taxon
        crumbs << [Spree.t(:products), products_path]
        crumbs += taxon.ancestors.collect { |a| [a.name, spree.nested_taxons_path(a.permalink)] } unless taxon.ancestors.empty?
        crumbs << [taxon.name, spree.nested_taxons_path(taxon.permalink)]
      else
        crumbs << [Spree.t(:products), products_path]
      end

      separator = raw(separator)

      crumbs.map! do |crumb|
        content_tag(:li, itemscope:"itemscope", itemtype:"http://data-vocabulary.org/Breadcrumb") do
          link_to(crumb.last, itemprop: "url") do
            content_tag(:span, crumb.first, itemprop: "title")
          end + (crumb == crumbs.last ? '' : separator)
        end
      end

      content_tag(:nav, content_tag(:ul, raw(crumbs.map(&:mb_chars).join), class: breadcrumb_class), id: 'breadcrumbs', class: 'sixteen columns')
    end

    def taxons_tree(root_taxon, current_taxon, max_level = 1)
      return '' if max_level < 1 || root_taxon.children.empty?
      content_tag :ul, class: 'taxons-list' do
        root_taxon.children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
          content_tag :li, class: css_class do
           link_to(taxon.name, seo_url(taxon)) +
           taxons_tree(taxon, current_taxon, max_level - 1)
          end
        end.join("\n").html_safe
      end
    end

    def available_countries
      checkout_zone = Zone.find_by(name: Spree::Config[:checkout_zone])

      if checkout_zone && checkout_zone.kind == 'country'
        countries = checkout_zone.country_list
      else
        countries = Country.all
      end

      countries.collect do |country|
        country.name = Spree.t(country.iso, scope: 'country_names', default: country.name)
        country
      end.sort_by { |c| c.name.parameterize }
    end

    def seo_url(taxon)
      return spree.nested_taxons_path(taxon.permalink)
    end

    def gem_available?(name)
       Gem::Specification.find_by_name(name)
    rescue Gem::LoadError
       false
    rescue
       Gem.available?(name)
    end

    def display_price(product_or_variant)
      product_or_variant.price_in(current_currency).display_price.to_html
    end

    def pretty_time(time)
      [I18n.l(time.to_date, format: :long),
        time.strftime("%l:%M %p")].join(" ")
    end

    def method_missing(method_name, *args, &block)
      if image_style = image_style_from_method_name(method_name)
        define_image_method(image_style)
        self.send(method_name, *args)
      else
        super
      end
    end

    def link_to_tracking(shipment, options = {})
      return unless shipment.tracking && shipment.shipping_method

      if shipment.tracking_url
        link_to(shipment.tracking, shipment.tracking_url, options)
      else
        content_tag(:span, shipment.tracking)
      end
    end

    private

    # Returns style of image or nil
    def image_style_from_method_name(method_name)
      if method_name.to_s.match(/_image$/) && style = method_name.to_s.sub(/_image$/, '')
        possible_styles = Spree::Image.attachment_definitions[:attachment][:styles]
        style if style.in? possible_styles.with_indifferent_access
      end
    end

    def create_product_image_tag(image, product, options, style)
      options.reverse_merge! alt: image.alt.blank? ? product.name : image.alt
      image_tag image.attachment.url(style), options
    end

    def define_image_method(style)
      self.class.send :define_method, "#{style}_image" do |product, *options|
        ActiveSupport::Deprecation.warn "Spree image helpers will be deprecated in the near future. Use the provided resource to access the intendend image directly.", caller
        options = options.first || {}
        if product.images.empty?
          if !product.is_a?(Spree::Variant) && !product.variant_images.empty?
            create_product_image_tag(product.variant_images.first, product, options, style)
          else
            if product.is_a?(Variant) && !product.product.variant_images.empty?
              create_product_image_tag(product.product.variant_images.first, product, options, style)
            else
              image_tag "noimage/#{style}.png", options
            end
          end
        else
          create_product_image_tag(product.images.first, product, options, style)
        end
      end
    end
  end
end

app/helpers/spree/checkout_helper.rb
module Spree
  module CheckoutHelper
    def checkout_states
      @order.checkout_steps
    end

    def checkout_progress
      states = checkout_states
      items = states.map do |state|
        text = Spree.t("order_state.#{state}").titleize

        css_classes = []
        current_index = states.index(@order.state)
        state_index = states.index(state)

        if state_index < current_index
          css_classes << 'completed'
          text = link_to text, checkout_state_path(state)
        end

        css_classes << 'next' if state_index == current_index + 1
        css_classes << 'current' if state == @order.state
        css_classes << 'first' if state_index == 0
        css_classes << 'last' if state_index == states.length - 1
        # It'd be nice to have separate classes but combining them with a dash helps out for IE6 which only sees the last class
        content_tag('li', content_tag('span', text), class: css_classes.join('-'))
      end
      content_tag('ol', raw(items.join("\n")), class: 'progress-steps', id: "checkout-step-#{@order.state}")
    end
  end
end

app/helpers/spree/orders_helper.rb
require 'truncate_html'
require 'app/helpers/truncate_html_helper'

module Spree
  module OrdersHelper
    include TruncateHtmlHelper

    def truncated_product_description(product)
      truncate_html(raw(product.description))
    end

    def order_just_completed?(order)
      flash[:order_completed] && order.present?
    end
  end
end

app/helpers/spree/products_helper.rb
module Spree
  module ProductsHelper
    # Returns the formatted price for the specified variant as a full price or
    # a difference depending on configuration
    #
    # @param variant [Spree::Variant] the variant
    # @return [Spree::Money] the price or price diff
    def variant_price(variant)
      if Spree::Config[:show_variant_full_price]
        variant_full_price(variant)
      else
        variant_price_diff(variant)
      end
    end

    # Returns the formatted price for the specified variant as a difference
    # from product price
    #
    # @param variant [Spree::Variant] the variant
    # @return [String] formatted string with label and amount
    def variant_price_diff(variant)
      variant_amount = variant.amount_in(current_currency)
      product_amount = variant.product.amount_in(current_currency)
      return if variant_amount == product_amount || product_amount.nil?
      diff   = variant.amount_in(current_currency) - product_amount
      amount = Spree::Money.new(diff.abs, currency: current_currency).to_html
      label  = diff > 0 ? :add : :subtract
      "(#{Spree.t(label)}: #{amount})".html_safe
    end

    # Returns the formatted full price for the variant, if at least one variant
    # price differs from product price.
    #
    # @param variant [Spree::Variant] the variant
    # @return [Spree::Money] the full price
    def variant_full_price(variant)
      product = variant.product
      unless product.variants.active(current_currency).all? { |v| v.price == product.price }
        Spree::Money.new(variant.price, { currency: current_currency }).to_html
      end
    end

    # Converts line breaks in product description into <p> tags.
    #
    # @param product [Spree::Product] the product whose description you want to filter
    # @return [String] the generated HTML
    def product_description(product)
      if Spree::Config[:show_raw_product_description]
        raw(product.description)
      else
        raw(product.description.gsub(/(.*?)\r?\n\r?\n/m, '<p>\1</p>'))
      end
    end

    # Filters and truncates the given description.
    #
    # @param description_text [String] the text to filter
    # @return [String] the filtered text
    def line_item_description_text(description_text)
      if description_text.present?
        truncate(strip_tags(description_text.gsub('&nbsp;', ' ')), length: 100)
      else
        Spree.t(:product_has_no_description)
      end
    end

    # @return [String] a cache invalidation key for products
    def cache_key_for_products
      count = @products.count
      max_updated_at = (@products.maximum(:updated_at) || Date.today).to_s(:number)
      "#{I18n.locale}/#{current_currency}/spree/products/all-#{params[:page]}-#{max_updated_at}-#{count}"
    end
  end
end

app/helpers/spree/store_helper.rb
module Spree
  # Methods added to this helper will be available to all templates in the
  # frontend.
  module StoreHelper
    # @return [Boolean] true when it is appropriate to show the store menu
    def store_menu?
      %w{thank_you}.exclude? params[:action]
    end

    def cache_key_for_taxons
      max_updated_at = @taxons.maximum(:updated_at).to_i
      parts = [@taxon.try(:id), max_updated_at].compact.join("-")
      "#{I18n.locale}/taxons/#{parts}"
    end
  end
end

app/views/spree/products/_cart_form.html.erb
<%= form_for :order, :url => populate_orders_path do |f| %>
  <div id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

    <% if @product.variants_and_option_values(current_currency).any? %>
      <div id="product-variants" class="  ">
        <h6 class="product-section-title"><%= Spree.t(:colors) %></h6>
        <ul>
          <% @product.variants_and_option_values(current_currency).each_with_index do |variant, index| %>
            <li>
              <%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => variant.price_in(current_currency).money  %>
              <%= label_tag "variant_id_#{ variant.id }" do %>
                <span class="variant-description">
                  <%= variant_options variant %>
                </span>
                <% if variant_price variant %>
                  <span class="price diff"><%= variant_price variant %></span>
                <% end %>

                <% unless variant.can_supply? %>
                  <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
                <% end %>
              <% end %>
            </li>
          <% end%>
        </ul>
      </div>
    <% else %>
      <%= hidden_field_tag "variant_id", @product.master.id %>
    <% end %>

    <% if @product.price_in(current_currency) and !@product.price.nil? %>
      <div data-hook="product_price" class="columns five <% if !@product.has_variants? %> alpha <% else %> omega <% end %>">

        <div id="product-price">
          <h6 class="product-section-title"><%= Spree.t(:price) %></h6>
          <div>
            <span class="price selling" itemprop="price">
              <%= display_price(@product) %>
            </span>
            <span itemprop="priceCurrency" content="<%= @product.currency %>"></span>
          </div>

          <% if @product.master.can_supply? %>
            <link itemprop="availability" href="http://schema.org/InStock" />
          <% elsif @product.variants.empty? %>
            <br />
            <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
          <% end %>
        </div>

        <div class="add-to-cart">
          <%= number_field_tag :quantity, 1, :class => 'title', :min => 1 %>
          </div>
        <div>
          <%= button_tag :class => 'large primary', :id => 'add-to-cart-button', :type => :submit do %>
            <%= Spree.t(:add_to_cart) %>
          <% end %>
        </div>
      </div>
    <% else %>
        <div id="product-price">
          <br>
          <div><span class="price selling" itemprop="price"><%= Spree.t('product_not_available_in_this_currency') %></span></div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/_hoverinfo.html.erb
<h4><%= hs.product_part.part.name %></h4>

<div id="name"><%= hs.product_part.description %> </div>

<p>
  <span><strong>Material:</strong> <%= hs.product_part.material.name %></span>
  <span>|</span>
  <span><strong>Origin:</strong> <%= hs.product_part.location.country %> </span>
  <br><br>
  <%= hs.product_part.material.description %></p>

app/views/spree/products/_image.html.erb
<style>
  circle {
    opacity: 0.4;
    fill: #fff;
    stroke: #000;
    stroke-width: 1px;
  }
  .current {
    stroke: #fff;
    fill: #000;
    opacity: 1;
  }

  .line{
    transform-origin: 0 0;
    height: 3px; /* Line width of 3 */
    background: #767676; /* Black fill */
  }
  #infobox {
    height: 50px;
    width: 100%;
    height: 250px;
    margin: 80px auto 0 auto;
  }
    #infobox svg {
      display: block;
      margin: auto;
      display: none;
    }

</style>

<% if defined?(image) && image %>
    <%= image_tag image.attachment.url(:product), itemprop: "image" %>
<% else %>

    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 240 240"  preserveAspectRatio="xMinYMin meet">

      <image width="240" height="160" xlink:href="<%= @product.display_image.attachment(:product) %>"> </image>


     <%= @product.visuals_product_perspectives.each do |perspect| %>

          <g id="hotspot<%= perspect.position %>">

            <%= perspect.hotspots.each do |hs| %>

                <a class="selector" title="

                <div><h4><%= hs.product_part.part.name %></h4></div>
                <section><%= hs.product_part.description %> </section>
                <div>
                <p>
                  <span><strong>Material:</strong> <%= hs.product_part.material.name %></span>
                  <span>|</span>
                  <span><strong>Origin:</strong> <%= hs.product_part.location.country %> </span>
                </p>
                </div>
                <section>
                <span><%= hs.product_part.material.description %></span>
                </section>
                ">

                  <circle class="" cx="<%= hs.offset_x %>" cy="<%= hs.offset_y %>" r="<%= hs.radius %>"></circle>
                </a>

            <%end%>

          </g>

      <% end %>


    </svg>

<% end %>

<!--


<%= render partial: "visuals/products/product_image_hotspots/#{@product.partial_name}/svg" %>


<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 240 240"  preserveAspectRatio="xMinYMin meet">

  <image width="240" height="240" xlink:href="<%= @product.display_image.attachment(:product) %>"> </image>

</svg>-->

<script type="text/javascript">

  $.fn.bootstrapSwitch.defaults.size = 'mini';
  $.fn.bootstrapSwitch.defaults.onColor = 'black';

  $("[name='toggler-checkbox']").bootstrapSwitch();

  $("[name='toggler-checkbox']").on('switchChange.bootstrapSwitch', function(event, state) {
    var thumbA;

    thumbA = $('#product-images ul.thumbnails li');

    console.log(" console logs thumbA as" + thumbA);

    var toggleId;
    if (($('#main-image')).hasClass('toggle')) {
      ($('#main-image')).removeClass('toggle');
    } else {
      ($('#main-image')).addClass('toggle');
    }
    toggleId = ($('.selected')).attr('id');
    ($(thumbA)).toggleClass("off");
    ($('#hotspot' + toggleId)).toggle();
    return console.log('#hotspot' + toggleId);
  });





  function createLine(x1, y1, x2, y2) {
    var length = Math.sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2));
    var angle = Math.atan2(y2 - y1, x2 - x1) * 180 / Math.PI;
    var transform = 'rotate('+angle+'deg)';
    var top;
    var left;

    if (y2 < y1) {
      top = y2;
      left = x1;
    }
    else {
      top = y1;
      left = x1;
    }

    var line = $('<div>')
        .appendTo('#main-image')
        .addClass('line')
        .css({
          'position': 'absolute',
          'transform': transform
        })
        .width(length)
        .offset({left: left, top: top});

    return line;
  }

  $(document).ready(function() {

    $('.selector').qtip({
      position: {
        my: 'top left',  // Position my top left...
        at: 'top left',
        target: $('#infobox')
      },
      show: {
        event: 'mouseenter',
        modal: {
          on: true,
          effect: function (state) {
            /*
             "state" determines if its hiding/showing
             "this" refers to the overlay
             0.4 and 0 are the show and hide opacities respectively.
             */
            $(this).fadeTo(500, state ? 0.5 : 0, function () {
              if (!state) {
                $(this).hide();
              }
            });
          },
        },
        solo: true,
        effect: function(offset) {
          $(this).show("slide", { direction: "left" }, 500); // "this" refers to the tooltip
        }
      },
      style: {
        width: '400px',
        classes: 'qtip-bootstrap',
        tip: {
          corner: false
        }
      },

      hide: {
        event: 'mouseleave',
        leave: false,

      },
      events: {
        show: function(event, api) {
          document.body.style.cursor = 'pointer';
        },

        hide: function(event, api) {
          document.body.style.cursor = 'default';
        }
      }
    });

    $('.selector').mouseover(function (event) {
      $(this).find('circle').attr("class", "hotspot current");
      $(this).find('circle').attr("r", "7");

      var x1 = event.target.getBoundingClientRect().x + 10 ,
          y1 = event.target.getBoundingClientRect().y + 10 ;

      var x0 = 100,
          y0 = 300;

      var changeX = x1 - x0 ,
          changeY = y0 - y1 ,
          slope = changeX / changeY;

      console.log("x1 " + x1);
      console.log("y1 " + y1);
      console.log("slope " + slope);

      var y2 = (slope * x0);
      var x2 = (slope * y0);

      /*
      createLine(x0,y0,x1,y1);


      var newLine = document.createElementNS('http://www.w3.org/2000/svg','line');
      newLine.setAttribute('class','line');
      newLine.setAttribute('x1','100');
      newLine.setAttribute('y1','100');
      newLine.setAttribute('x2',event.target.getBoundingClientRect().x);
      newLine.setAttribute('y2',event.target.getBoundingClientRect().y);
      $(this).parent().append(newLine);

*/

    });

    $('.selector').mouseout(function () {
      $(this).find('circle').attr("class", "hotspot");
      $(this).find('circle').attr("r", "5");

       $('.line').fadeOut(300, function(){ $(this).remove(); });
    });



  });
</script>

app/views/spree/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>
<% if promotions.any? %>
  <div id="promotions">
    <h3><%= Spree.t(:promotions) %></h3>
    <% promotions.each do |promotion| %>
    <div>
      <h4><%= promotion.name %></h4>
      <p><%= promotion.description %></p>
      <% if promotion.products.any? %>
      <ul>
        <% promotion.products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/_properties.html.erb
<% unless @product_properties.empty? %>  
  <h6 class="product-section-title"><%= Spree.t('properties')%></h6>
  <div id="product-properties" data-hook>

      <% @product_properties.each do |product_property| %>
        <% css_class = cycle('even', 'odd', :name => "properties") %>
        <ol>
          <li><strong><%= product_property.property.presentation %></strong></li>
          <li><%= product_property.value %></li>
        </ol>
      <% end %>
      <% reset_cycle('properties') %>
</div>
<% end %>

app/views/spree/products/_taxons.html.erb
<% if !@product.taxons.blank? %>
  <div id="taxon-crumbs" data-hook class="alpha columns five omega">
    <h6 class="product-section-title"><%= Spree.t(:look_for_similar_items) %></h6>

    <div data-hook="product_taxons">
      <ul id="similar_items_by_taxon" data-hook>
      <% @product.taxons.each do |taxon| %>
        <li><%= link_to taxon.name, seo_url(taxon) %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/spree/products/_thumbnails.html.erb
<%# no need for thumbnails unless there is more than one image %>
<% if (@product.images + @product.variant_images).uniq.size > 1 %>
  <ul id="product-thumbnails" class="thumbnails inline" data-hook>
    <% @product.images.each do |i| %>
      <li id="<%= i.visuals_product_perspective.position %>" class='tmb-all tmb-<%= i.viewable.id %>'>
        <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
      </li>
    <% end %>

    <% if @product.has_variants? %>
      <% @product.variant_images.each do |i| %>
        <% next if @product.images.include?(i) %>
        <li id="<%= i.visuals_product_perspective.position %>" class='vtmb tmb-<%= i.viewable.id %>'>
          <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/spree/products/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <% if "spree/products" == params[:controller] && @taxon %>
      <%= render :partial => 'spree/shared/filters' %>
    <% else %>
      <%= render :partial => 'spree/shared/taxonomies' %>
    <% end %>
  </div>
<% end %>


<% if params[:keywords] %>

  <div data-hook="search_results">
    <% if @products.empty? %>
      <h6 class="search-results-title"><%= Spree.t(:no_products_found) %></h6>
    <% else %>
      <%= render :partial => 'spree/shared/products', :locals => { :products => @products, :taxon => @taxon } %>
    <% end %>
  </div>

<% else %>

  <div id="product-view" data-hook="homepage_products">
    <%= render :partial => 'spree/shared/products', :locals => { :products => @products, :taxon => @taxon } %>
  </div>

<% end %>